compress_assets: off
gzip_assets: off

javascripts:
  app:  
  # - public/javascripts/jquery.js
    - public/javascripts/jquery.*.js
    - public/javascripts/rails.js
    - public/javascripts/application.js
    - public/javascripts/application.*.js
stylesheets:
  app:
    - public/stylesheets/*.css
